import { ReferenceData } from "./types.ts";

const referenceData: ReferenceData = {
  "ProfessionalGroups": {
    "ProfessionalGroup": [
      {
        "Code": 1,
        "Description": "Artsen",
        "DescriptionEnglish": "Doctor of medicine",
        "Title": "Arts",
        "Article3": true,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 2,
        "Description": "Tandartsen",
        "DescriptionEnglish": "Dentist",
        "Title": "Tandarts",
        "Article3": true,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 3,
        "Description": "Verloskundigen",
        "DescriptionEnglish": "Midwife",
        "Title": "Verloskundige",
        "Article3": true,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 4,
        "Description": "Fysiotherapeuten",
        "DescriptionEnglish": "Physiotherapist",
        "Title": "Fysiotherapeut",
        "Article3": true,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 16,
        "Description": "Psychotherapeuten",
        "DescriptionEnglish": "Psychotherapist",
        "Title": "Psychotherapeut",
        "Article3": true,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 17,
        "Description": "Apothekers",
        "DescriptionEnglish": "Pharmacist",
        "Title": "Apotheker",
        "Article3": true,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 18,
        "Description": "Apotheekhoudende artsen",
        "DescriptionEnglish": "Dispensing GP",
        "Title": "Apotheekhoudende artsen",
        "Article3": false,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 84,
        "Description": "Klinisch Fysici",
        "DescriptionEnglish": "Clinical physicist",
        "Title": "Klinisch fysicus",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 25,
        "Description": "Gz-psychologen",
        "DescriptionEnglish": "Healthcare psychologist",
        "Title": "Gezondheidszorgpsycholoog",
        "Article3": true,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 30,
        "Description": "Verpleegkundigen",
        "DescriptionEnglish": "Nurse",
        "Title": "Verpleegkundige",
        "Article3": true,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 81,
        "Description": "Physician assistants",
        "DescriptionEnglish": "Physician assistant",
        "Title": "Physician assistant",
        "Article3": true,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 82,
        "Description": "Klinisch technologen",
        "DescriptionEnglish": "Technical Physician",
        "Title": "Klinisch technoloog",
        "Article3": true,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 87,
        "Description": "Optometristen",
        "DescriptionEnglish": "Optometrist",
        "Title": "Optometrist",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 88,
        "Description": "Huidtherapeuten",
        "DescriptionEnglish": "Skin therapist",
        "Title": "Huidtherapeut",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 89,
        "Description": "Diëtisten",
        "DescriptionEnglish": "Dietician",
        "Title": "Diëtist",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 90,
        "Description": "Ergotherapeuten",
        "DescriptionEnglish": "Occupational therapist",
        "Title": "Ergotherapeut",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 91,
        "Description": "Logopedisten",
        "DescriptionEnglish": "Speech and language therapist",
        "Title": "Logopedist",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 92,
        "Description": "Mondhygiënisten",
        "DescriptionEnglish": "Dental hygienist",
        "Title": "Mondhygiënist",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 93,
        "Description": "Oefentherapeuten Mensendieck",
        "DescriptionEnglish": "Mensendieck (remedial) therapist",
        "Title": "Oefentherapeut Mensendieck",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 94,
        "Description": "Oefentherapeuten Cesar",
        "DescriptionEnglish": "Cesar (remedial) therapist",
        "Title": "Oefentherapeut Cesar",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 95,
        "Description": "Orthoptisten",
        "DescriptionEnglish": "Orthoptist",
        "Title": "Orthoptist",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 96,
        "Description": "Podotherapeuten",
        "DescriptionEnglish": "Podotherapist",
        "Title": "Podotherapeut",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 97,
        "Description": "Radiodiagnostisch laboranten",
        "DescriptionEnglish": "Diagnostic radiographer",
        "Title": "Radiodiagnostisch laborant",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 98,
        "Description": "Radiotherapeutisch laboranten",
        "DescriptionEnglish": "Therapeutic radiographer",
        "Title": "Radiotherapeutisch laborant",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 99,
        "Description": "Onbekend",
        "DescriptionEnglish": "Unknown",
        "Title": "Onbekend",
        "Article3": false,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 83,
        "Description": "Apothekersassistenten",
        "DescriptionEnglish": "Pharmaceutical assistant",
        "Title": "Apothekersassistenten",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 85,
        "Description": "Tandprothetici",
        "DescriptionEnglish": "Dental technician",
        "Title": "Tandprotheticus",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 86,
        "Description": "Verzorgenden individuele gezondheidszorg",
        "DescriptionEnglish": "Nurse in individual healthcare (assistant nurse)",
        "Title": "Verzorgende individuele gezondheidszorg",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 80,
        "Description": "Bachelor Medisch Hulpverleners (tijdelijke BIG-registratie)",
        "DescriptionEnglish": "Allied Medical Care Professional (temporary BIG registration)",
        "Title": "Bachelor Medisch Hulpverlener (tijdelijke BIG-registratie)",
        "Article3": false,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 31,
        "Description": "Orthopedagogen-generalist",
        "DescriptionEnglish": "Remedial educationalist",
        "Title": "Orthopedagoog-generalist",
        "Article3": true,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 32,
        "Description": "Regieverpleegkundigen",
        "DescriptionEnglish": "Regional nurse",
        "Title": "regieverpleegkundige",
        "Article3": false,
        "Article34": false,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
      {
        "Code": 79,
        "Description": "Geregistreerd-mondhygiënisten (tijdelijke BIG-registratie)",
        "DescriptionEnglish": "Registered dental hygienist (temporary BIG registration)",
        "Title": "Geregistreerd-mondhygiënist (tijdelijke BIG-registratie)",
        "Article3": false,
        "Article34": true,
        "BusinessOwner": 1,
        "RequiredHoursForReregistration": 0,
      },
    ],
  },
  "TypeOfSpecialisms": {
    "TypeOfSpecialism": [
      {
        "Code": 2,
        "Description": "Allergologie",
        "DescriptionEn": "Allergology",
        "TitleOfSpecialist": "Allergoloog",
        "TitleOfSpecialistEn": "Allergology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 8,
        "Description": "Arbeid en gezondheid - bedrijfsgeneeskunde",
        "DescriptionEn": "Occupational medicine",
        "TitleOfSpecialist": "Bedrijfsarts",
        "TitleOfSpecialistEn": "Occupational medicine",
        "Register": "sociaal geneeskundigen",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 10,
        "Description": "Cardiologie",
        "DescriptionEn": "Cardiology",
        "TitleOfSpecialist": "Cardioloog",
        "TitleOfSpecialistEn": "Cardiology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 11,
        "Description": "Cardio-thoracale chirurgie",
        "DescriptionEn": "Thoracic surgery",
        "TitleOfSpecialist": "Cardiothoracaal chirurg",
        "TitleOfSpecialistEn": "Cardio-thoracic surgery",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 13,
        "Description": "Maag-darm-leverziekten",
        "DescriptionEn": "Gastroenterology",
        "TitleOfSpecialist": "Arts van maag-darm-leverziekten",
        "TitleOfSpecialistEn": "Gastroenterology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 14,
        "Description": "Heelkunde",
        "DescriptionEn": "General surgery",
        "TitleOfSpecialist": "Chirurg",
        "TitleOfSpecialistEn": "General surgery",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 15,
        "Description": "Huisartsgeneeskunde",
        "DescriptionEn": "General practice",
        "TitleOfSpecialist": "Huisarts",
        "TitleOfSpecialistEn": "General practice/family medicine",
        "Register": "Huisartsen",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 16,
        "Description": "Interne geneeskunde",
        "DescriptionEn": "General (internal) medicine",
        "TitleOfSpecialist": "Internist",
        "TitleOfSpecialistEn": "Internal medicine",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 19,
        "Description": "Kindergeneeskunde",
        "DescriptionEn": "Paediatrics",
        "TitleOfSpecialist": "Kinderarts",
        "TitleOfSpecialistEn": "Paediatrics",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 20,
        "Description": "Klinische chemie",
        "DescriptionEn": "Biological chemistry",
        "TitleOfSpecialist": "Arts klinische chemie",
        "TitleOfSpecialistEn": "Chemical pathology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 21,
        "Description": "Klinische genetica",
        "DescriptionEn": "Medical genetics",
        "TitleOfSpecialist": "Klinisch geneticus",
        "TitleOfSpecialistEn": "Medical genetics",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 22,
        "Description": "Klinische geriatrie",
        "DescriptionEn": "Geriatrics",
        "TitleOfSpecialist": "Klinisch geriater",
        "TitleOfSpecialistEn": "Geriatrics",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 23,
        "Description": "Longziekten en tuberculose",
        "DescriptionEn": "Respiratory medicine",
        "TitleOfSpecialist": "Longarts",
        "TitleOfSpecialistEn": "Pulmonary diseases and tuberculosis",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 24,
        "Description": "Medische microbiologie",
        "DescriptionEn": "Microbiology-bacteriology",
        "TitleOfSpecialist": "Arts-microbioloog",
        "TitleOfSpecialistEn": "Medical microbiology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 25,
        "Description": "Neurochirurgie",
        "DescriptionEn": "Neurological surgery",
        "TitleOfSpecialist": "Neurochirurg",
        "TitleOfSpecialistEn": "Neurosurgery [2005/36/EC: neurological surgery]",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 26,
        "Description": "Neurologie",
        "DescriptionEn": "Neurology",
        "TitleOfSpecialist": "Neuroloog",
        "TitleOfSpecialistEn": "Neurology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 30,
        "Description": "Nucleaire geneeskunde",
        "DescriptionEn": "Nuclear medicine",
        "TitleOfSpecialist": "Nucleair geneeskundige",
        "TitleOfSpecialistEn": "Nuclear medicine",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 31,
        "Description": "Oogheelkunde",
        "DescriptionEn": "Ophthalmology",
        "TitleOfSpecialist": "Oogarts",
        "TitleOfSpecialistEn": "Ophthalmology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 32,
        "Description": "Orthopedie",
        "DescriptionEn": "Orthopaedics",
        "TitleOfSpecialist": "Orthopedisch chirurg",
        "TitleOfSpecialistEn": "Orthopaedics",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 34,
        "Description": "Plastische chirurgie",
        "DescriptionEn": "Plastic surgery",
        "TitleOfSpecialist": "Plastisch chirurg",
        "TitleOfSpecialistEn": "Plastic surgery",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 35,
        "Description": "Psychiatrie",
        "DescriptionEn": "Psychiatry",
        "TitleOfSpecialist": "Psychiater",
        "TitleOfSpecialistEn": "Psychiatry",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 39,
        "Description": "Radiologie",
        "DescriptionEn": "Diagnostic radiology",
        "TitleOfSpecialist": "Radioloog",
        "TitleOfSpecialistEn": "Diagnostic radiology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 40,
        "Description": "Radiotherapie",
        "DescriptionEn": "Radiotherapy",
        "TitleOfSpecialist": "Radiotherapeut",
        "TitleOfSpecialistEn": "Radiotherapy",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 43,
        "Description": "Maatschappij en gezondheid (vervallen)",
        "DescriptionEn": "Community medicine",
        "TitleOfSpecialist": "Arts maatschappij en gezondheid",
        "TitleOfSpecialistEn": "Public health medicine",
        "Register": "sociaal geneeskundigen",
        "EndDate": "2007-01-01T00:00:00",
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 45,
        "Description": "Urologie",
        "DescriptionEn": "Urology",
        "TitleOfSpecialist": "Uroloog",
        "TitleOfSpecialistEn": "Urology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 50,
        "Description": "Zenuw- en zielsziekten",
        "DescriptionEn": "Neuropsychiatry",
        "TitleOfSpecialist": "Zenuwarts",
        "TitleOfSpecialistEn": "Neuropsychiatry",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 54,
        "Description": "Mondziekten en Kaakchirurgie",
        "DescriptionEn": "Oral diseases and dental surgery",
        "TitleOfSpecialist": "MKA-chirurg",
        "TitleOfSpecialistEn": null,
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 2,
      },
      {
        "Code": 56,
        "Description": "Geneeskunde voor verstandelijk gehandicapten",
        "DescriptionEn": "Medicine for the mentally disabled",
        "TitleOfSpecialist": "Arts voor verstandelijk gehandicapten",
        "TitleOfSpecialistEn": "Medical care for the mentally handicapped",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 61,
        "Description": "Klinische psychologie",
        "DescriptionEn": "Clinical psychology",
        "TitleOfSpecialist": "Klinisch psycholoog",
        "TitleOfSpecialistEn": null,
        "Register": "Klinisch psychologen",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 25,
      },
      {
        "Code": 62,
        "Description": "Interne geneeskunde-allergologie",
        "DescriptionEn": "Allergology",
        "TitleOfSpecialist": "Internist-allergoloog",
        "TitleOfSpecialistEn": "Allergology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 70,
        "Description": "Jeugdgezondheidszorg (Profiel KNMG Jeugdarts)",
        "DescriptionEn": "A youth health care physician",
        "TitleOfSpecialist": "Jeugdarts",
        "TitleOfSpecialistEn": "A youth health care physician",
        "Register": "SGRC",
        "EndDate": "2018-01-01T10:02:06",
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 75,
        "Description": "Openbare Farmacie",
        "DescriptionEn": "Public pharmacy",
        "TitleOfSpecialist": "Openbaar apotheker",
        "TitleOfSpecialistEn": "Community pharmacist",
        "Register": "openbaar apothekers",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 17,
      },
      {
        "Code": 76,
        "Description": "Algemene Gezondheidszorg (AGZ)",
        "DescriptionEn": "Somatic health care",
        "TitleOfSpecialist": "Verpl. spec. algemene gezondheidszorg",
        "TitleOfSpecialistEn": "Somatic health care",
        "Register": "Specialismen Verpleegkunde",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 30,
      },
      {
        "Code": 74,
        "Description": "Sportgeneeskunde",
        "DescriptionEn": "Sport medicine",
        "TitleOfSpecialist": "Sportarts",
        "TitleOfSpecialistEn": "Sport medicine",
        "Register": "sportartsen",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 65,
        "Description": "Preventieve zorg bij somatische aandoeningen",
        "DescriptionEn": "Preventive care in somatic disorders",
        "TitleOfSpecialist": "Verpl. spec. prev. zorg bij som. aandoeningen",
        "TitleOfSpecialistEn": "Preventive care in somatic disorders",
        "Register": "Specialismen Verpleegkunde",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 30,
      },
      {
        "Code": 66,
        "Description": "Acute zorg bij somatische aandoeningen",
        "DescriptionEn": "Acute care in somatic disorders",
        "TitleOfSpecialist": "Verpl. spec. acute zorg bij som. aandoeningen",
        "TitleOfSpecialistEn": "Acute care in somatic disorders",
        "Register": "Specialismen Verpleegkunde",
        "EndDate": "2021-01-01T11:12:08",
        "ProfessionalGroupCode": 30,
      },
      {
        "Code": 67,
        "Description": "Intensieve zorg bij somatische aandoeningen",
        "DescriptionEn": "Intensive care in somatic disorders",
        "TitleOfSpecialist": "Verpl. spec. intensieve zorg bij som. aandoeningen",
        "TitleOfSpecialistEn": "Intensive care in somatic disorders",
        "Register": "Specialismen Verpleegkunde",
        "EndDate": "2021-01-01T11:14:24",
        "ProfessionalGroupCode": 30,
      },
      {
        "Code": 68,
        "Description": "Chronische zorg bij somatische aandoeningen",
        "DescriptionEn": "Chronic care in somatic disorders",
        "TitleOfSpecialist": "Verpl. spec. chronische zorg bij som. aandoeningen",
        "TitleOfSpecialistEn": "Chronic care in somatic disorders",
        "Register": "Specialismen Verpleegkunde",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 30,
      },
      {
        "Code": 69,
        "Description": "Geestelijke Gezondheidszorg",
        "DescriptionEn": "Mental health care",
        "TitleOfSpecialist": "Verpl. spec. geestelijke gezondheidszorg",
        "TitleOfSpecialistEn": "Mental health care",
        "Register": "Specialismen Verpleegkunde",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 30,
      },
      {
        "Code": 71,
        "Description": "Spoedeisendehulp  (Profiel SEH Arts KNMG)",
        "DescriptionEn": null,
        "TitleOfSpecialist": "Spoedeisende hulp arts",
        "TitleOfSpecialistEn": null,
        "Register": "KNMG",
        "EndDate": "2018-01-01T10:03:13",
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 60,
        "Description": "Ziekenhuisfarmacie",
        "DescriptionEn": "Hospital pharmacy",
        "TitleOfSpecialist": "Ziekenhuisapotheker",
        "TitleOfSpecialistEn": "Hospital pharmacist",
        "Register": "ziekenhuisapothekers",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 17,
      },
      {
        "Code": 55,
        "Description": "Maatschappij en gezondheid",
        "DescriptionEn": "Community medicine",
        "TitleOfSpecialist": "Arts maatschappij en gezondheid",
        "TitleOfSpecialistEn": "Public health medicine",
        "Register": "sociaal geneeskundigen",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 53,
        "Description": "Dento-maxillaire orthopaedie",
        "DescriptionEn": "Orthodontics",
        "TitleOfSpecialist": "Orthodontist",
        "TitleOfSpecialistEn": null,
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 2,
      },
      {
        "Code": 48,
        "Description": "Arbeid en gezondheid - verzekeringsgeneeskunde",
        "DescriptionEn": "Occupational medicine",
        "TitleOfSpecialist": "Verzekeringsarts",
        "TitleOfSpecialistEn": "Occupational medicine",
        "Register": "sociaal geneeskundigen",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 47,
        "Description": "Specialisme ouderengeneeskunde",
        "DescriptionEn": "Geriatric medicine",
        "TitleOfSpecialist": "Specialist ouderengeneeskunde",
        "TitleOfSpecialistEn": "Geriatric medicine",
        "Register": "Specialist ouderengeneeskunde",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 46,
        "Description": "Obstetrie en gynaecologie",
        "DescriptionEn": "Obstetrics and Gynaecology",
        "TitleOfSpecialist": "Gynaecoloog",
        "TitleOfSpecialistEn": "Obstetrics and Gynaecology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 4,
        "Description": "Huisartsgeneeskunde met apotheek (Apoth. Huisarts)",
        "TitleOfSpecialist": "Apotheekhoudend huisarts",
        "Register": "Huisartsen",
        "EndDate": "2020-06-23T15:31:37.207",
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 42,
        "Description": "Revalidatiegeneeskunde",
        "DescriptionEn": "Physiotherapy",
        "TitleOfSpecialist": "Revalidatiearts",
        "TitleOfSpecialistEn": "Rehabilitation [2005/36/EC: physiotherapy]",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 41,
        "Description": "Reumatologie",
        "DescriptionEn": "Rheumatology",
        "TitleOfSpecialist": "Reumatoloog",
        "TitleOfSpecialistEn": "Rheumatology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 33,
        "Description": "Pathologie",
        "DescriptionEn": "Pathological anatomy",
        "TitleOfSpecialist": "Patholoog",
        "TitleOfSpecialistEn": "Pathology [2005/36/EC: pathological anatomy]",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 18,
        "Description": "Keel-, neus- en oorheelkunde",
        "DescriptionEn": "Otorhinolaryngology",
        "TitleOfSpecialist": "Keel- neus- oorarts",
        "TitleOfSpecialistEn": "Otolaryngology/otorhinolaryngology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 12,
        "Description": "Dermatologie en venerologie",
        "DescriptionEn": "Dermato-venereology",
        "TitleOfSpecialist": "Dermatoloog",
        "TitleOfSpecialistEn": "Dermato-venereology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
      {
        "Code": 63,
        "Description": "Klinische neuropsychologie",
        "DescriptionEn": "Clinical neuropsychology",
        "TitleOfSpecialist": "Klinisch neuropsycholoog",
        "TitleOfSpecialistEn": null,
        "Register": "Klinisch psychologen",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 25,
      },
      {
        "Code": 3,
        "Description": "Anesthesiologie",
        "DescriptionEn": "Anaesthetics",
        "TitleOfSpecialist": "Anesthesioloog",
        "TitleOfSpecialistEn": "Anaesthesiology",
        "Register": "medisch specialisten",
        "EndDate": {
          "@xsi:nil": true,
          "#text": null,
        },
        "ProfessionalGroupCode": 1,
      },
    ],
  },
};

export default referenceData;
